### ISSUE TITLE
Custom Widget built from cookie cutter not working in Jupyter Lab 3.0

### ISSUE THREAD

**Issue by cornhundred** [jupyter-widgets/widget-ts-cookiecutter#116]
Hi, I am having trouble getting a Jupyter Widget that was built by @thomasballinger using this template working in Jupyter Lab 3.0 (it works in Jupyter notebook)

I raised the issue [here](https://github.com/thomasballinger/observable-jupyter-widget/issues/3#issuecomment-1136388253) and I'll summarize below:

I'm seeing the following error when I try to open the widget in JupyterLab

523.92b431af199caa12622d.js:1 Error: Module observable-jupyter-widget, semver range ^0.1.8 is not registered as a widget module
    at x.loadClass (523.92b431af199caa12622d.js:1:5727)
    at x.<anonymous> (272.eb0d340d1eec40ac564f.js:1:9479)
    at 272.eb0d340d1eec40ac564f.js:1:6081
    at Object.next (272.eb0d340d1eec40ac564f.js:1:6186)
    at 272.eb0d340d1eec40ac564f.js:1:5122
    at new Promise (<anonymous>)
    at D (272.eb0d340d1eec40ac564f.js:1:4867)
    at x.e._make_model (272.eb0d340d1eec40ac564f.js:1:9358)
    at x.<anonymous> (272.eb0d340d1eec40ac564f.js:1:9212)
    at 272.eb0d340d1eec40ac564f.js:1:6081
I'm thinking it might be related to this issue:
https://github.com/jupyter-widgets/widget-ts-cookiecutter/issues/39

Here's a link to a [Code Ocean capsule](https://codeocean.com/capsule/5548056/tree) that reproduces the issue - works in Jupyter Notebook and does not run in Jupyter Lab - this capsule does a good job of capturing the compute environment.
